### ISSUE TITLE
Secondary account: plugin not working

### ISSUE THREAD

**Issue by esseti** [MyOutDeskLLC/auto-bcc#2]
Hello,
I've more than one single account from which I'm able to send emails.
In settings -> accounts -> Send email as: (there i've two accounts)

The extension works only from the principal email, and not for the second.
In addition, even if I create an email and select my second account as sender, it still applies the rule for the first account.

Do you by any chance ignore this multiple account possibility? is something that can be fixed?

**Comment by tance77** [comment]
I'll try to replicate this when I get some free time. It's been a hot minute since I worked on the project. Thanka for the bug report.

**Comment by rossc719g** [comment]
I am seeing the same thing, and sadly, this is my exact use case for this tool.

I.e., My partner and I have our own gmail accounts, but also a shared one.
We can both "Send email as" the shared account.
The problem is, that if I send or reply as the shared account, my partner will not see it unless I bcc the shared account as well.

I was hoping to set it up so that when I "Send as the shared account" it will bcc it too, but it seems like this only works for the primary user.

**Comment by tance77** [comment]
This will now support multiple send addresses in version 1.6

**Comment by rossc719g** [comment]
> This will now support multiple send addresses in version 1.6

That's great.
I'll try to sneak in a fix for https://github.com/MyOutDeskLLC/auto-bcc/issues/6 quickly.  Hopefully you can roll it into 1.6 too?

Also, on the topic of a new release.. it looks like a `npm audit` might be a good idea:
```
6 vulnerabilities (1 low, 2 moderate, 2 high, 1 critical)

To address all issues, run:
  npm audit fix
```

**Comment by tance77** [comment]
@rossc719g I already merged it into master will have to rebase. Thanks for that ill update the modules on the next Pull Request.
